{"level": "DEBUG", "message": "debug message", "timestamp": "2024-06-26T14:33:20.494970+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-06-26T14:33:20.495194+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-06-26T14:33:20.495321+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-06-26T14:33:20.495531+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-06-26T14:33:20.495741+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-06-26T14:33:20.495960+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 35, "thread_name": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"/app/main.py\", line 33, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2024-06-26T14:34:37.020691+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-06-26T14:34:37.021006+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-06-26T14:34:37.021192+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-06-26T14:34:37.021399+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-06-26T14:34:37.021589+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-06-26T14:34:37.021796+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 35, "thread_name": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"/app/main.py\", line 33, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2024-06-26T14:34:44.374163+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-06-26T14:34:44.374558+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-06-26T14:34:44.374789+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-06-26T14:34:44.375007+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-06-26T14:34:44.375227+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-06-26T14:34:44.375456+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 35, "thread_name": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"/app/main.py\", line 33, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2024-06-26T14:38:45.495050+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-06-26T14:38:45.495376+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-06-26T14:38:45.495574+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-06-26T14:38:45.495798+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-06-26T14:38:45.496006+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-06-26T14:38:45.496200+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 35, "thread_name": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"/app/main.py\", line 33, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2024-06-26T14:40:57.210371+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread", "x": "hello"}
{"level": "INFO", "message": "info message", "timestamp": "2024-06-26T14:40:57.210586+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2024-06-26T14:40:57.210715+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2024-06-26T14:40:57.210936+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2024-06-26T14:40:57.211139+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message", "timestamp": "2024-06-26T14:40:57.211351+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 35, "thread_name": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"/app/main.py\", line 33, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero"}
